---
version: "3.7"
services:
  autoshift:
    image: autoshift:latest
    environment:
      - SHIFT_USER=foo
      - SHIFT_PASS=/run/secrets/gearbox_password
      - SHIFT_GAMES=bl3
      - SHIFT_PLATFORMS=epic
    secrets:
      - gearbox_password
    deploy:
      replicas: 1
secrets:
  gearbox_password:
    external: true
...